### ISSUE TITLE
AttributeError: 'DummyComm' object has no attribute 'kernel'

### ISSUE THREAD

**Issue by pllim** [ipython/comm#14]
@maartenbreddels , using your #13 fix, now I get this downstream in Jdaviz. Hope you can help. Thanks!

`AttributeError: 'DummyComm' object has no attribute 'kernel'`

Example log: https://github.com/spacetelescope/jdaviz/actions/runs/4482254804/jobs/7895309668?pr=2104

xref https://github.com/spacetelescope/jdaviz/pull/2104

**Comment by martinRenou** [comment]
Thanks for reporting! This is an issue in ipywidgets: https://github.com/jupyter-widgets/ipywidgets/pull/3733
