### ISSUE TITLE
NameError: name 'get_comm_manager' is not defined

### ISSUE THREAD

**Issue by maclandrol** [ipython/comm#8]
In version `0.10`, line 109  raises an error:
https://github.com/ipython/comm/blob/457b37cb3b40514d556dfd29a83098dd75724faa/comm/base_comm.py#L93-L109

because `get_comm_manager` is not imported. This seems to be the only release available and is installed in my env with latest ipython ecosystem.

**Comment by martinRenou** [comment]
Thank you, this has been fixed by https://github.com/ipython/comm/commit/e9f49fcc71c39d9c9751ee9ff291f54110d3aeda
